steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nihongo-sprinter:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/nihongo-sprinter:latest', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nihongo-sprinter:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nihongo-sprinter:latest']
  
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nihongo-sprinter'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nihongo-sprinter:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/$PROJECT_ID/nihongo-sprinter:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/nihongo-sprinter:latest'

timeout: '1200s'
